### PR TITLE
feat: remove HP reminder

### LINKED ISSUE #10: Remove CON remider
remove the string "(Don't forget to add your constitution bonus)"

### PR DESCRIPTION
**Pull request by DoNotResuscitate**
New rules state CON bonus should not be added to your HP.
Fixes #10

### CODE REVIEW

**Comment by Gulluth** [comment]
So we can't base this bot on the contents of the Deluxe Edition, since those rules are not covered by Community Commons. We need to continue to support what is stated in the SRD, and CON bonus is still added to HP.

**Comment by DoNotResuscitate** [comment]
@Gulluth in the linked issue you stated the SRD also removed the con bonus which is what I was basing it on - I admittedly have not checked the SRD itself yet.

**Comment by Gulluth** [comment]
Interesting, Let me review specifically where this was discussed with Leo to confirm, and will close #10. We don't need this message, so will go ahead and merge. I will also get the SRD updated with the corrected info. Thanks for your contribution.

**Review by Gulluth — APPROVED** [review]
GTG

**Pull request merged**
